### ISSUE TITLE
which version of logstash

### ISSUE THREAD

**Issue by ragogitpub** [yokawasa/logstash-output-documentdb#2]
Hello

What version of logstash have you tested with ?

I am having issues with various versions of jruby, rest-client, mime-types and logstash-core.

if you could clarify that would be great. Better yet if it works with latest version that would be nice too.

**Comment by yokawasa** [comment]
The logstash version I've tested with is logstash 2.1.3.

Here is info on my testing environment:
OS:  Ubuntu 15.10
Logstash: 2.1.3
jruby --versionjruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d OpenJDK 64-Bit Server VM 25.66-b17 on 1.8.0_66-internal-b17 +jit [linux-amd64]

**Comment by yokawasa** [comment]
@ragogitpub 
I've just fixed the issue #3. I'm not sure but it may be the same issue that you've experienced, and if so, it can be resolved by installing the latest version

logstash-output-documentdb-0.1.2
https://rubygems.org/gems/logstash-output-documentdb/versions/0.1.2
https://github.com/yokawasa/logstash-output-documentdb/releases/tag/v0.1.2

**Comment by paulpc** [comment]
@yokawasa , any plans for 5.x support?

**Comment by yokawasa** [comment]
@paulpc  Thanks for your interest in logstash-output-documentdb! I'll work on 5.X support next week and update

**Comment by yokawasa** [comment]
@paulpc 
Just released logstash-output-documentdb-0.2.0 which supports logstash 5.X
https://github.com/yokawasa/logstash-output-documentdb/releases/tag/v0.2.0
